### ISSUE TITLE
Invalid value encountered in true_divide in MDA function for fsfg example

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/atomistic-parsers#13]
Problem:
.../MDAnalysis/core/groups.py:1099: RuntimeWarning: invalid value encountered in true_divide
  _centers /= _weights.sum(axis=1)[:, None]

Note:
This may somehow be related to the memory issue in the Rg test which uses the fsfg example.

**Comment by ladinesa** [comment]
Please uncomment the relevant test I outcommented last time and include it in the pr.

**Comment by JFRudzinski** [comment]
> Please uncomment the relevant test I outcommented last time and include it in the pr.

This is done. Please check now.
