### ISSUE TITLE
Generalization of MD workflow results

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/atomistic-parsers#19]
The workflow results (e.g., rdf/msd) are currently calculated in each atomistic parser from the MDA instances created from the corresponding raw files. These calculations should be moved to the normalization step and be computed from a (generalized) MDA instance created directly from the nomad metainfo.
nb - as a side effect, we should store the references to each molecule / molecule group for these observables using the topology structure with the results section.

(NOMAD issue [#1199](https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/issues/1199))

**Comment by JFRudzinski** [comment]
@ladinesa: I am mostly done with these changes, just going to do some additional tests tomorrow. I left in a bunch of commented out older sections and some comments. I'm not sure if you want to look at the code first, but at some point I would like to meet with you to discuss a few changes that I have made and make sure that you agree with the overall approach. Perhaps if you have time tomorrow or Mon? I will be on vacation starting next Wed, so it would be good to merge this before then so that you can combine it with your other workflow changes.

Note that there is a corresponding NOMAD branch: [1199](https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/compare/develop...1199-generalization-of-md-workflow-results)  That you will also have to look at.

**Comment by ladinesa** [comment]
Can you please make a draft PR for this so I can review it? Thanks. also in gitlab.

**Comment by JFRudzinski** [comment]
> Can you please make a draft PR for this so I can review it? Thanks. also in gitlab.

done.
