### ISSUE TITLE
Lammps parser hangs within parse_method() for new example

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/atomistic-parsers#2]
I am having trouble with this new lammps example. I placed it under `tests/data/lammps/polymer_melt/Equil/` in my `md-workflow-observables` branch. The corresponding nomad branch is `970-add-RDF-MSD-plots-to-overview-GUI-page-for-molecular-dynamics-trajectories`. 

When I try to parse `nohup.out` the parser hangs (at least for 10-20 min) at line 1181 `masses = self.data_parser.get('Masses', None)` in lammps/parser.py. If I set `masses=None` on this line instead, everything finishes correctly in ~10s. The data_parser.mainfile is correct, and I see the "Masses" section within this file. So, I don't understand what is happening and I'm unsure how to debug this. At some point during my testing the parsing worked correctly with this line in there but took a long time. But all my changes (to my knowledge) have to do with `parse_workflow() `so I can't see how I have caused this problem.

Another related issue/confusion is the following: Here I am parsing `nohup.out `which is the screen output when I run the lammps simulation. The native output file `log.lammps `has a similar header but does not contain any of the input info like `read_data` and such. So, I cannot parse this one successfully. @ladinesa :  Have you experienced this? Is it meant that we parse the screen output and not the native lammps log file??

**Comment by ladinesa** [comment]
I put up a fix in md-workflow-observables. Can you try it? If the fix works, I will apply it to the master branch

**Comment by JFRudzinski** [comment]
I'm getting an error now: `TypeError: _log() got an unexpected keyword argument 'data'` when parsing `nohup.out`. Do you have an idea of what the issue is?

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/work/soft/nomad/nomad/parsing/file_parser/text_parser.py in _add_value(self, quantity, value, units)
    386         try:
--> 387             value_processed = quantity.to_data(value)
    388             for i in range(len(value_processed)):

~/work/soft/nomad/nomad/parsing/file_parser/text_parser.py in to_data(self, val_in)
    217 
--> 218         val_out = [process(val) for val in val_in]
    219 

~/work/soft/nomad/nomad/parsing/file_parser/text_parser.py in <listcomp>(.0)
    217 
--> 218         val_out = [process(val) for val in val_in]
    219 

~/work/soft/nomad/nomad/parsing/file_parser/text_parser.py in process(val)
    159             if self.str_operation is not None:
--> 160                 val = self.str_operation(val)
    161 

~/work/soft/nomad/dependencies/parsers/atomistic/atomisticparsers/lammps/parser.py in get_section_value(val)
    147 
--> 148             if val[0][0] == '#':
...
-> 1390             self._log(WARNING, msg, args, **kwargs)
   1391 
   1392     def warn(self, msg, *args, **kwargs):

TypeError: _log() got an unexpected keyword argument 'data'

**Comment by ladinesa** [comment]
I missed one more fix, should be included now in latest commit.

**Comment by JFRudzinski** [comment]
indeed, it works now :+1:
