### ISSUE TITLE
Lammps parser doesn't recognize variables in the log file

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/atomistic-parsers#3]
Need to extend the Lammps parser to read and replace variables when reading input information. See `nohup_w_variables.out` (original) vs `nohup.out` (manually edited) in `tests/data/lammps/polymer_melt/Equil`

**Comment by ladinesa** [comment]
@JFRudzinski can we close this?

**Comment by JFRudzinski** [comment]
Yes, I have no plans to fix this anytime soon.

**Comment by JFRudzinski** [comment]
I will leave this on backlog instead

**Comment by JFRudzinski** [comment]
I've looked into this some more now. The functionality of variables within the Lammps input script is too complex for us to support IMO. Perhaps in the future if someone came with particular sub-functionalities that they really need support for we could have a discussion, but for now it does not make sense to invest time into this.
