### ISSUE TITLE
Super class for MD parsers

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/atomistic-parsers#32]
We can perhaps make a super class for MD parsers, which deals with repeated functions like parts of parse_thermodynamic_data() and the frame rate sampling.

**Comment by ladinesa** [comment]
I just recently thought about this also. I can work on this if you like.

**Comment by JFRudzinski** [comment]
Yes, that would be good. Let's keep in contact about it though. I don't want to lose track of what is happening within these parsers, or else it will be increasing difficult for me to deal with user issues.
