### ISSUE TITLE
missing system references for Gromacs data

### ISSUE THREAD

**Issue by JFRudzinski** [nomad-coe/atomistic-parsers#66]
When the superclass for atomistic parsers was implemented it changed the way that Gromacs system references are being assigned. Before the calculation and system lists were being matched by time (if available), and now they are matched by step. 

The problem is that we are using MDAnalysis to obtain this information for system. The times are assigned correctly by MDA, but the steps do not correspond to the actual simulation step, but rather just an index for the *stored* trajectory frames.

We need to either go back to first trying to match by times for any data using the MDA util, or for Gromacs data we could alternatively grab the steps directly from the .trr/.xtc files (which are stored correctly). 

@ladinesa what do you think? Can you address this?

**Comment by JFRudzinski** [comment]
sorry, here is an example you can look at `tests/data/parsers/gromacs/protein_small_nowater/md.log` from the nomad tests

**Comment by ladinesa** [comment]
sorry for causing the mess.i will fix this asap. although i still am.not sure why it fails.

**Comment by JFRudzinski** [comment]
np, thank you!

It is just because the MDAnalysis universe is not storing the steps from the trajectory file. It indexes each from of the trajectory simply with 0,1,2,3,.... But it doesn't take into account the save frequency of the simulation. E.g., in the simulation I referenced, save freq is 100, so the thermo data (read directly from the edr file) has steps 0, 100, 200, 300,... instead.
